workflows:
  flutter-app:
    name: Flutter Calculator
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.rana.trilingual_calculator"
    scripts:
      - name: Flutter build
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@gmail.com
